### ISSUE TITLE
터미널 에뮬레이터에서 글리프가 반으로 잘려 보입니다.

### ISSUE THREAD

**Issue by unstabler** [quiple/hbios-sys#2]
![Screenshot_20220816_100712](https://user-images.githubusercontent.com/964412/184771476-76154fd9-65f6-413c-8dfa-d2ffdd4d278a.png)

# 이슈 내용
- 글리프가 반으로 잘려서 보이는 문제가 있는 것 같습니다!
- 터미널 에뮬레이터는 Konsole (KDE Plasma 22.04)를 사용하고 있습니다.

# 기타
개인적으로 HBIOS 폰트를 굉장히 좋아하는데, 트루타입 폰트로 만들어 주셔서 정말 감사합니다!

**Comment by quiple** [comment]
LineGap이 2px 위로 차지하고 있어서 생긴 문제였던 것 같아요..! LineGap을 0으로 만들고 일단 WSL에 Konsole 설치해서 제대로 보이는 걸 확인했는데 확인 부탁드려요.

**Comment by unstabler** [comment]
bdf 폰트로 확인해보니 잘 나옵니다! 감사합니다!
