### ISSUE TITLE
비례 버전 다운로드 링크 주소가 잘못된 것 같습니다.

### ISSUE THREAD

**Issue by kunggom** [quiple/hbios-sys#3]
HBIOS-SYS 홈페이지(https://hbios.quiple.dev/)의 ‘알려진 문제’ 섹션을 보면, **비례 버전**의 폰트를 제공하고 있는 것으로 나옵니다.

그런데 해당 링크의 주소는 현재 다음과 같이 되어 있습니다.
이는 ‘다운로드’ 섹션에 있는 기존 TTF 버전 파일의 다운로드 주소와 동일합니다.
`https://github.com/quiple/hbios-sys/raw/main/HBIOS-SYS.ttf`

**비례 버전**에 링크하려고 했던 파일은 아마도 이것으로 보입니다.
`https://github.com/quiple/hbios-sys/raw/main/HBIOS-SYS-prop.ttf`

링크 수정이 필요합니다.

**Comment by quiple** [comment]
이걸 눈치를 못 챘네요..; 수정했습니다.
